### ISSUE TITLE
Is this project still alive? :-)

### ISSUE THREAD

**Issue by cosimosimeoneTR** [bio4j/bio4j-neo4j#12]
Hi there Guys! How's life?
Quick, simple and direct question: is this project still alive? :-)
No updates in almost one month, lots of TODOs in documentation, 404 behind any corner...

Any news? :-) 
THANKS, ciao!
Cosimo

**Comment by eparejatobes** [comment]
hey @cosimosimeoneTR bio4j is pretty much alive, but all the action is in bio4j/bio4j and bio4j/bio4j-titan. 

If you're wondering about a Neo4j-backed Bio4j, we stopped using Neo4j ~2 years ago. If there's interest though, we could easily implement a Neo4j version and import everything; it's just not a priority right now.

Ping me on gitter: https://gitter.im/bio4j/bio4j for anything, it's way better than issues for this kind of question.

cheers
