### ISSUE TITLE
trying not to wrap Neo4j nodes

### ISSUE THREAD

**Issue by eparejatobes** [bio4j/bio4j-neo4j#5]
I don't like (performance reasons) that in the current implementation we are wrapping everywhere the Neo4j `Node`s into classes. In the end, these classes are not actually needed because
1. for import, we can just create the raw data and access the required node label etc through an interface instead (static final var)
2. actually getting data is always done through the database, be it either indexes or the result of methods that can be implemented using the Neo4j `Node` methods

@bio4j/coders what do you think?

**Comment by laughedelic** [comment]
Either I didn't understand you, or you told me the opposite a week ago. How do we reflect the abstract model then? And will we need to type-cast these nodes to the bio4j classes that implement the model?

**Comment by eparejatobes** [comment]
@laughedelic wait for the code :)

**Comment by eparejatobes** [comment]
crap, not possible. We will keep doing the wrapping thing

**Comment by eparejatobes** [comment]
I will have the start of this later in the evening

**Comment by laughedelic** [comment]
:cry: but what did you try to do?

**Comment by eparejatobes** [comment]
see #1

**Comment by eparejatobes** [comment]
not possible, closing
